'''
    Orchestrator facade to expose API:
'''

class Orchestrator:

    def __init__(self, **kwargs):
        self.plan_repo = kwargs['plan_repo']
        self.plan_exec = kwargs['plan_exec']
        self.plan_parser = kwargs['plan_parser']

    def submit_plan_for_execution(self, plan_json):
        '''
        Executes submitted plan.

        Algorithm:
            parse plan JSON
            save the plan and get back plan id
            trigger plan execution

        :param plan_json: json string describing a plan
        :return: plan_id: Autogenerated id of submitted plan
        '''

        plan = self.plan_parser.parse_plan_json(plan_json)
        plan_id = self.plan_repo.save_plan(plan)
        self.plan_exec.execute_plan(plan_id)

        return plan_id
